// File generated by flutterfire CLI - placeholder for CI builds without Firebase
class DefaultFirebaseOptions {
  static const FirebaseOptions currentPlatform = FirebaseOptions(
    apiKey: 'AIzaSyPlaceholderKeyForCIBuild',
    appId: '1:000000000000:android:00000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'times-up-placeholder',
    storageBucket: 'times-up-placeholder.appspot.com',
  );
}

class FirebaseOptions {
  const FirebaseOptions({
    required this.apiKey,
    required this.appId,
    required this.messagingSenderId,
    required this.projectId,
    required this.storageBucket,
  });

  final String apiKey;
  final String appId;
  final String messagingSenderId;
  final String projectId;
  final String storageBucket;
}
